### ISSUE TITLE
Bootstrap's JavaScript requires jQuery

### ISSUE THREAD

**Issue by acmoune** [css-modules/css-modules-require-hook#100]
I am using `css-modules-require-hook` to render a react app on the server, but I am having the `Error: Bootstrap's JavaScript requires jQuery`.

With client side webpack I fix it with this plugin config:

```javascript
plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jquery: "jquery",
      "window.jQuery": "jquery",
      jQuery:"jquery"
    })
]
```
How can I proceed server side, using `css-modules-require-hook` ?

Thanks in advance.

**Comment by sullenor** [comment]
Hello,

Unfortunately,  `css-modules-require-hook` doesn't add any browser environment. 
You may try to add a custom polyfill to the nodejs environment via `global` variable, `jsdom` and `jquery` packages.

**Comment by acmoune** [comment]
Thanks for your reply @sullenor
