### ISSUE TITLE
Working only with preset (and .conf.js) and does not work 'manually'

### ISSUE THREAD

**Issue by sambhav-gore** [css-modules/css-modules-require-hook#110]
The readme describes two ways to use - Manually OR with preset and conf

Of the two, only the preset is working for me and the other one throws error. 

My cmrh.conf.sj is as following

~~~
// cmrh.conf.js

const sass = require("node-sass");

module.exports = {
  generateScopedName: "navigation_[local]__[hash:base64:5]",
  extensions: [ '.scss', '.css' ],
  "preprocessCss": (data, filename) =>
    sass.renderSync({
      data,
      file: filename,
    }).css,
};

~~~

I was hoping to better organize the code by converting it to a lib in my project. 

The error I get WHEN NOT USING a conf file is as following:

```shell
/PATH_TO_PROJECT/src/components/navigation.scss:1
(function (exports, require, module, __filename, __dirname) { .nav_wrapper {

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    .
    .
    .
    .

```
.nav_wrapper is first style in my scss file.

**Comment by sullenor** [comment]
Looks like `navigation.scss` file is processed as a js file, so that's why you get a parsing exception.
You need to register a require-hook just before you make any require to the css file.

So need to put `require('css-modules-require-hook');` if you use a preset file or setup it manually:

```
const hook = require('css-modules-require-hook');

hook({
  // setup
});
```

**Comment by sambhav-gore** [comment]
@sullenor Thank you. Yes I did not notice that the component was required before the preset is applied. If I apply the immediately after declaring the hook then it works correctly.

closing this issue.
