### ISSUE TITLE
CSSNext support

### ISSUE THREAD

**Issue by sheepsteak** [css-modules/css-modules-require-hook#19]
I have Webpack set up using `cssnext-loader` and then `css-loader?modules` for the client-side. However, for the server there's no way to preprocess the CSS before the require hook runs it through PostCSS. How could I have CSSNext process the file first before it hits the require hook? 

Is it best that this is made into it's own require hook or could there be an extra parameter passed in (`preprocess`) that allows you to run the CSS through CSSNext first (or possibly LESS/SASS??)

**Comment by sullenor** [comment]
Recently I thought about similar functionality. Unfortunately, currently `require-hook` supports only PostCSS plugins, which you can customize through the `use` option and there is no other way to preprocess CSS before the require hook runs it through PostCSS.

I think I can add another option to make it possible, but there are some restrictions, imposed by require function - all transformations should be synchronous.

**Comment by sullenor** [comment]
I'm not sure, but looks like CSSNext is based on the [PostCSS plugins](https://github.com/postcss/postcss#future-css-syntax), so can they solve your problem?

If yes, you can setup the `require-hook` like this:
```javascript
var hook = require('css-modules-require-hook');

hook({
  use: [
    // custom
    require('postcss-custom-selectors'),
    // css-modules
    require('postcss-modules-extract-imports'),
    require('postcss-modules-local-by-default'),
    require('postcss-modules-scope')
  ]
});
```

**Comment by sheepsteak** [comment]
Yeah, CSSNext is just a collection of PostCSS plugins that roughly gives you >=CSS4 syntax.

I did think about putting the plugins in `use`, but then there is the fact you'd have to keep it the same as the plugins used by `cssnext` I think (use the same order, etc.) to get parity with the webpack `cssnext-loader`. I guess that's not a massive problem and maybe it's better to not use CSSNext anyway and just pick the PostCSS plugins I do actually want to use.

**Comment by sheepsteak** [comment]
I just found that CSSNext can be used as a [PostCSS plugin] itself! This solves all the problems so I'll close this.

Thanks for your help!

**Comment by sullenor** [comment]
Thank you for the information, I'll put it to the readme.
