### ISSUE TITLE
declare Node version requirement

### ISSUE THREAD

**Issue by pocketjoso** [css-modules/css-modules-require-hook#20]
Hi, thanks for nice library,
I was stuck with the error below for a while before I figured out that my Node version (0.10.38) didn't have  the required `path.parse` method:

```
var parsed = (0, _path.parse)(pathname);
                               ^
TypeError: undefined is not a function
    at isModule (/Users/jso/criticalcss/node_modules/css-modules-require-hook/dist/index.js:113:32)
```
Error went away after upgrading to Node `0.12.7`.

---
Perhaps you can declare this requirement a bit more explicitly in README somewhere (or guard and throw clearer error)?

Thanks again for great repo!

**Comment by sullenor** [comment]
Hi, thanks :)

I need a fresh version of Node.JS to make it easier to resolve paths for windows. I used `engine` property in the package.json file, but seems to me npm v2.x doesn't check it.
I'll make it more explicit and put information to the readme.

**Comment by nkbt** [comment]
Hi, @sullenor, just use `nvm` to install multiple node and iojs versions, so you can easily switch between them

**Comment by sullenor** [comment]
@nkbt Hi, thanks for the tip. Honestly I need `path.sep` property, which is different for windows and mac OS. I need to it to resolve paths in a correct way. And it is available since 0.12.x version.

**Comment by nkbt** [comment]
Use path.resolve and/or path.join, you would hardly need a path.sep.

**Comment by sullenor** [comment]
When you work with multiple dependencies - path to the new sources can be absolute, relative or an external module and it becomes challenging to resolve them.

I found out a good way to work with them, but I need to build absolute paths for that, which are relative to the root directory. For that I use [path.sep](https://github.com/css-modules/css-modules-require-hook/blob/master/src/index.js#L98-L108) property.

If you know how to solve it without `path.sep` - please, tell me :)

**Comment by sullenor** [comment]
Put it to readme
[1.0.5](https://github.com/css-modules/css-modules-require-hook/releases/tag/1.0.5)
