### ISSUE TITLE
remove shortcut aliases?

### ISSUE THREAD

**Issue by DenisIzmaylov** [css-modules/css-modules-require-hook#26]
Hi all? What to do you think about making more strong API with removing aliases (`root` and `d` for `rootDir`, `u` for `use`)? In first 2-3 months we can just add warning message of using deprecated options.

**Comment by sullenor** [comment]
Done: [2.0.0](https://github.com/css-modules/css-modules-require-hook/releases/tag/2.0.0)

**Comment by DenisIzmaylov** [comment]
Congrats!
