### ISSUE TITLE
usage with webpack's preprocessors ?

### ISSUE THREAD

**Issue by geekyme** [css-modules/css-modules-require-hook#35]
I couldn't get the hook to work with my webpack's configurations for preprocessed stylesheets (in stylus). 

My webpack config: 

```
{ test: /\.styl$/, loader: "style!css?modules&importLoaders=2&sourceMap&localIdentName=[name]-[local]-[hash:base64:5]!stylus!autoprefixer?browsers=last 2 version" }
```

the stylus file:
```
@import "./constants/colors"
@import "./constants/typography"
@import "./utils/normalize"

html
  -webkit-tap-highlight-color rgba(0, 0, 0, 0)
body
  color $color-primary
  background $color-white
  font-size $font-size
  font-family $font-family
  font-weight 300
html,
body,
#root
  height 100%
a
  color $color-secondary
h1
  font-weight 300
  text-align center
```

the component using the style:
```
import styles from "../style/Application.styl";

console.log(styles)

class App extends Component {
    .....
}
```

how i register the hook on server.js: 
```
// Enable css modules to be loaded on the server side
require("css-modules-require-hook")({
  extensions: [".styl"]
});
....
```

when logging `styles`, I expected to see Object { root: ... }, however I just see an empty object { }.

**Comment by sullenor** [comment]
Hi, thank you for the code example. Let me explain the way to use any preprocessing functions.

Basically, the `extensions` option attaches the require hook to the provided file extensions. It doesn't make any assumptions about them :)
If you want to preprocess css before it will be passed to the postcss pipeline, you use provide custom function through the `preprocessCss` option. For example:
```javascript
var hook = require('css-modules-require-hook');
hook({
  extensions: ['.styl'],
  preprocessCss: function (css, filename) {
    // css = modify(css);
    return css;
  }
});
```

However the is a restriction coming for the `require` function - all transformations should be synchronous.
Unfortunately, I haven't found any synchronous API provided by stylus yet.

**Comment by sullenor** [comment]
Oh, good news, I have found a pr to the stylus, which makes synchronous transformations possible:
https://github.com/stylus/stylus/pull/934

I managed to build a working example, so I assume, you can start with it:
```javascript
var stylus = require('stylus');
var hook = require('css-modules-require-hook');

hook({
  extensions: ['.styl'],
  preprocessCss: function (css, filename) {
    return stylus(css).render();
  }
});

var css = require('./demo.styl');
console.log(css);
```

**Comment by geekyme** [comment]
Yes this works now thank you.

**Comment by geekyme** [comment]
By the way since my CSS is actually generated by webpack, is there any use for the postProcess hook?

**Comment by sullenor** [comment]
Yes, there is another option called `processCss`. I added it for the Electron's support.
I suppose it is possible to generate final CSS with it also.
Since it will be called for each required file on the server side, you need to be sure, that you require all the necessary styles and accumulate them somewhere :)
