### ISSUE TITLE
referenced class name in composes not found

### ISSUE THREAD

**Issue by sebastienbarre** [css-modules/css-modules-require-hook#38]
Hi. I'm using `webpack` but testing with `mocha`. How would you do unit tests with css-modules / css-loader? It was suggested I use `css-modules-require-hook` but I'm getting errors related to `composes`:
```
CssSyntaxError: postcss-modules-scope: /src/css/Vote.css:2:3: referenced class name "i__imported_large_0" in composes not found
.voteButton {
  composes: large from "./typography.css";
```
where `src/css/Vote.css` is:
```css
.voteButton {
  composes: large from "./typography.css";
}
```
and `src/css/typography.css` is:
```css
.large {
  font-size: 1.5rem;
}
```
and `src/components/Vote.jsx` (being tested) starts with:
```javascript
import React from 'react/addons';
import styles from '../css/Vote.css';
```
I'm testing with:
```
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js 'test/**/*.@(js|jsx)'",
```
and my `test/test_helper.js` contains:
```javascript
var hook = require('css-modules-require-hook');
var path = require('path');

hook({
  // setting root to the parent directory
  rootDir: path.join(__dirname, '..')
});
```
It fails the same way if I don't change `rootDir`...
Thank you. Keep up with the great work!

**Comment by sullenor** [comment]
Hi, I see two possible problems.
- The first one is that your `imports` were resolved before the require hook was adjusted.
- The second one is that you need to adjust the way your class names are generated.

I assume that you don't want to change your webpack config and setting up require hook to generate class names in the same way can be challenging :)
I have a small example to help you here: https://github.com/sullenor/universal-demo/blob/master/server.js#L10-L22
If you can provide your webpack config, I think I can help you with adjusting it.

**Comment by sullenor** [comment]
Also I published a beta version to help you with debugging. You should be able to download it with providing its version:
```javascript
npm i css-modules-require-hook@1.0.9
```
To run it in the debugging mode you should specify the environment variable `DEBUG=css-modules:*`.
It will help you to see if the require hook was adjusted before the first test occurred or not.

**Comment by sullenor** [comment]
Oh, I haven't noticed in the beginning, looks like its a problem with a scope plugin itself. Can you post the versions of your plugins, so I can look on the problem?

**Comment by sebastienbarre** [comment]
Thanks for the quick reply @sullenor ; I will try the debugging mode later tonight. I certainly don't mind adjusting my webpack config. In the meantime:
From `package.json`:
```
  "devDependencies": {
    "autoprefixer": "^6.0.3",
    "babel-core": "^5.8.25",
    "babel-eslint": "^4.1.3",
    "babel-loader": "^5.3.2",
    "chai": "^3.3.0",
    "chai-immutable": "^1.3.0",
    "commitizen": "^1.0.4",
    "conventional-changelog": "^0.4.3",
    "css-loader": "^0.19.0",
    "css-modules-require-hook": "^1.0.8",
    "cssnano": "^3.2.0",
    "cz-conventional-changelog": "1.1.0",
    "eslint": "^1.5.1",
    "eslint-plugin-smells": "^1.0.1",
    "extract-text-webpack-plugin": "^0.8.2",
    "ghooks": "^0.3.2",
    "jsdom": "^3.1.2",
    "mocha": "^2.3.3",
    "postcss": "^5.0.8",
    "postcss-loader": "^0.6.0",
    "postcss-modules-extract-imports": "0.0.6",
    "postcss-modules-local-by-default": "0.0.12",
    "postcss-modules-scope": "0.0.8",
    "react-hot-loader": "^1.3.0",
    "semantic-release": "^4.3.5",
    "style-loader": "^0.12.4",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.0"
  },
  "dependencies": {
    "immutable": "^3.7.5",
    "react": "^0.13.3",
    "react-redux": "^3.0.0",
    "react-router": "^0.13.3",
    "redux": "^3.0.2",
    "socket.io-client": "^1.3.7"
  }
```
My `webpack.config.js`:
```
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var autoprefixer = require('autoprefixer');
var cssLoaderOptions = '?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]';

module.exports = {
  entry: [
    'webpack-dev-server/client?http://localhost:9090',
    'webpack/hot/only-dev-server',
    './src/index.jsx'
  ],
  module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'react-hot!babel'
    }, {
      test: /\.css$/,
      loader: ExtractTextPlugin.extract(
        'style-loader', 'css-loader' + cssLoaderOptions + '!postcss-loader'
      )
    }]
  },
  postcss: [
    autoprefixer({ browsers: ['last 2 versions'] })
  ],
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  output: {
    path: __dirname + '/dist',
    publicPath: '/',
    filename: 'bundle.js'
  },
  devServer: {
    contentBase: './dist',
    hot: true
  },
  plugins: [
     new ExtractTextPlugin('style.css', { allChunks: true }),
     new webpack.HotModuleReplacementPlugin()
  ]
};
```
Thanks for the help.

**Comment by sebastienbarre** [comment]
With debugging enabled:
```
barre@killy /Users/src/voting-client (master)$ export DEBUG=css-modules:*
barre@killy /Users/src/voting-client (master)$ npm test

> @sebastienbarre/voting-client@0.0.0-semantically-released test /Volumes/Users/src/voting-client
> mocha --compilers js:babel-core/register --require ./test/test_helper.js 'test/**/*.@(js|jsx)'

  css-modules:setup { rootDir: '/Volumes/Users/src/voting-client' } +0ms
  css-modules:fetch /Volumes/Users/src/voting-client/src/css/Vote.css +201ms
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#after is deprecated. Use Node#raws.after

/Volumes/Users/src/voting-client/node_modules/postcss/lib/lazy-result.js:204
            throw error;
                  ^
CssSyntaxError: postcss-modules-scope: /src/css/Vote.css:2:3: referenced class name "i__imported_large_0" in composes not found
.voteButton {
  composes: large from "./typography.css";
```
I've to say I'm not sure I understand why I need `generateScopedName`. Isn't the goal of CSS Modules that I shouldn't have to worry about the resulting class names?
Thanks

**Comment by sebastienbarre** [comment]
Update: thanks, turns out reverting to `postcss` ^4.0.0 solved the issue.

**Comment by sullenor** [comment]
@sebastienbarre Sorry, I haven't got time to look on it, but I'm happy to know that you managed to solve the issue :)

Actually, all the plugins have to be updated in order to work with the fresh version of PostCSS and I think that necessary pr's have already been made, but I don't know when they will be shipped. I suppose that there is a beta version of css-loader, but I'm not sure.

Getting back to your question about generating class names. All the class names are generated automatically, but there are two ways to generate them by default.
The first one is described in the scope plugin and the second one is provided by webpack loader. Loader also provides you a nice API to set up a pattern instead of the function. I'm using the first one in the require hook by default. Honestly I haven't done any API to support the second one yet, so in order to get the same result with require hook and webpack - you need to set up in manually.

**Comment by bradbarrow** [comment]
I've encountered this same issue with an almost identical use case - running mocha with css-modules-require-hook in the required entry file.

```
require('babel/register');
require('babel/polyfill');
require('css-modules-require-hook')({
  generateScopedName: function(exportedName, path) {
    return exportedName;
  }
});
```

**Comment by bradbarrow** [comment]
Running with the debugger shows that it has setup the `generatedScopeName` function before it fetches any files, so I'd assuming naming should be consistent throughout?

css-modules:setup { generateScopedName: [Function] } +0ms

css-modules:fetch /Users/projects/app/src/components/CardSlider/CardSlider.css +811ms
css-modules:fetch /Users/projects/app/src/components/ListingCard/ListingCard.css +36ms
css-modules:fetch /Users/projects/app/src/components/WatchButton/WatchButton.css +41ms
css-modules:fetch /Users/projects/app/src/components/Button/Button.css +20ms
css-modules:fetch /Users/projects/app/src/components/Heading/Heading.css +170ms
css-modules:fetch /Users/projects/app/src/components/FormFields/Input/Input.css +61ms

/Users/projects/app/node_modules/postcss/lib/lazy-result.js:204
throw error;
^
CssSyntaxError: postcss-modules-scope: /src/components/FormFields/Input/Input.css:3:3: referenced class name "i__imported_formField_0" in composes not found
{
composes: formField from '../FormFields.css'
            ^
}
  at Input.error (/Users/projects/app/node_modules/postcss/lib/input.js:61:21)
at Declaration.error (/Users/projects/app/node_modules/postcss/lib/node.js:70:38)
  at /Users/projects/app/node_modules/postcss-modules-scope/lib/index.js:120:24
at Array.forEach (native)
  at /Users/projects/app/node_modules/postcss-modules-scope/lib/index.js:108:17
  at /Users/projects/app/node_modules/postcss/lib/container.js:102:34

**Comment by sullenor** [comment]
@bradbarrow Can you check the version of the PostCSS package? I assume that the problem comes from the latest versions. The fourth version should work perfectly.

**Comment by bradbarrow** [comment]
@sullenor thanks for getting back.

Do you mean installing that version of PostCSS in my own app?

```
npm install postcss@4.0.0
```

followed by running my mocha command yields the following:


```
/Users/user/dev/app/projects/app/node_modules/css-modules-require-hook/dist/parser.js:11
exports['default'] = (0, _postcss.plugin)('parser', function parser() {
    ^
    TypeError: (0 , _postcss.plugin) is not a function
    at Object.<anonymous> (/Users/user/dev/app/projects/app/node_modules/css-modules-require-hook/dist/parser.js:11:42)
    at Module._compile (module.js:426:26)
    at Module._extensions..js (module.js:444:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/dev/app/projects/app/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:351:32)})
```

**Comment by bradbarrow** [comment]
Hmm

```
rm -rf node_modules
npm install --save postcss@4.0.0 css-modules-require-hook
rm -rf node_modules
npm install
```

All working fine now. Not sure what the story is here. Something to be kept on the radar though if it's broken in newer versions of postcss. Thanks again

**Comment by sullenor** [comment]
@bradbarrow yeah, the version of PostCSS in your app. I think you can provide `4.x` simply.

The problem is in the old version of plugins. PostCSS@5.x introduced the new version of plugins API which isn't compatible with the fourth version. So, to fix it all the plugins should be updated.

**Comment by mmrko** [comment]
I've found the following setup to work when using Mocha to test React Components that use CSS Modules: https://gist.github.com/mmrko/288d159a55adf1916f71
