### ISSUE TITLE
generateScopedName generates different hash than css-loader

### ISSUE THREAD

**Issue by canvaskisa** [css-modules/css-modules-require-hook#48]
Thanks, for making such cool feature as generateScopedName, but combining it with webpack's css-loader gives me different results.
Here is `css-modules-require-hook` config: 
```
require('css-modules-require-hook')({
  generateScopedName: '[name]__[local]___[hash:base64:5]',
  mode: 'local'
});
```

And here is webpack's css-loader config:
```
{ 
      test: /\.css$/, 
      loader: 'style!css?modules&localIdentName=[name]__[local]___[hash:base64:5]!postcss',
      include: [
        path.resolve(__dirname, '..', 'app')
      ]
}
```

So hooks result is `index__navitem___2ntrM`, but css-loader's: `index__navitem___1gRhv`.

What can be wrong with config or is this hook's bug?

**Comment by sullenor** [comment]
Can you check the version of the css-loader you use? It should be v0.21.0 or higher.
Also `context` field in the webpack config can make a difference. You should provide `rootDir` to the require-hook if it isn't a current working directory.

**Comment by canvaskisa** [comment]
css-loader version is "^0.21.0", and so webpack's context and hook's rootDir are equivalent.

**Comment by sullenor** [comment]
Well, looks like a bug, I'll try to check it out.

**Comment by sullenor** [comment]
yeah, you were right. I found it and solved the problem. Thanks again :)
Try out the new version please: [2.0.1](https://github.com/css-modules/css-modules-require-hook/releases/tag/2.0.1)

**Comment by canvaskisa** [comment]
Now everything works like a charm, thanks a lot!

**Comment by sullenor** [comment]
Thanks :)

**Comment by StevenIseki** [comment]
Thanks, I had the same issue, upgrading to version `0.21.0` of **css-loader** and using `3.0.0-beta` of** css-modules-require-hook** as in your demo, now everything is working nicely.

**Comment by sullenor** [comment]
:smile: :+1:
