### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by markuplab** [css-modules/css-modules-require-hook#50]
CSS map changes doesn't apply, if module was changed.
It's due all modules in node js exposed as cached objects.
All reference saved in `require.cache`.

This tiny helper, that we use for clear `require.cache`:

```
  /**
   * Clears node.js require cache by key.
   * @param {string} key Cache key.
   */
  function clearCacheKey (key) {
    delete require.cache[key];
  }
```

**Comment by sullenor** [comment]
Yeah, that's true. Node.js caches all the require calls by default.
I assume you use this feature for the development needs only.

I think, I can add a check for the environment variable `NODE_ENV` and if it's equal to `development`, then clean cache from the require calls. Something similar to this: https://github.com/reactjs/express-react-views/blob/master/index.js#L59-L66

**Comment by markuplab** [comment]
Yes, it's for development workaround. env var is good idea.

**Comment by markuplab** [comment]
@sullenor When you can fix it?

**Comment by sullenor** [comment]
@markuplab I'll try tomorrow

**Comment by sullenor** [comment]
done, [2.1.0](https://github.com/css-modules/css-modules-require-hook/releases/tag/2.1.0)

**Comment by yazonnile** [comment]
Hey, everybody.
Thx, for great module!

I have some minor problem. Actually it`s not a problem at the moment, but think it could make some in future.

I'm talking about this https://github.com/reactjs/express-react-views/blob/master/index.js#L59-L66
Think `NODE_ENV = "development"` is very wide thing. And I would prefer something like this
```js
var initHooks = require('css-modules-require-hook');
initHooks({
	generateScopedName: generateScopedName(config),
	extensions: config.extensions.styles,
	preprocessCss,
	processCss,
	debug: true // <------------------
});
```
 to make cache cleaning sort of isolated. Just for that module. Without any influence to some other.
And this `debug: true` will make all that things that now are made by `NODE_ENV="development"`

Is that possible?

**Comment by yazonnile** [comment]
**#56 add pr**

**Comment by sullenor** [comment]
Looks like you have a slightly different name of the option in the pr :)

I don't mind to have a stronger option to control environment and I think its a good enhancement.

Sorry for the late call, I'll make the new version soon.

**Comment by yazonnile** [comment]
oops, my bad :)

>  I'll make the new version soon.

Wait for it. Good luck!

**Comment by sullenor** [comment]
@yazonnile should be available for now. Check out [2.1.1](https://github.com/css-modules/css-modules-require-hook/releases/tag/2.1.1)

**Comment by yazonnile** [comment]
Great! Thx!
