### ISSUE TITLE
Comparision to postcss-modules solution

### ISSUE THREAD

**Issue by NogsMPLS** [css-modules/css-modules-require-hook#52]
I just came across this repo: https://github.com/outpunk/postcss-modules

I'm curious as how these two solutions compare to each other.

Are they trying to achieve the same goal?

**Comment by sullenor** [comment]
Hi, currently I figured out that postcss-modules is another postcss plugin, which contains all the necessary packages for the CSS Modules.

I think it's similar to the [css-modules-loader-core](https://github.com/css-modules/css-modules-loader-core), but wrapped in the postcss-plugin, so you'll have a usual API. It can be used as a low-level module to build tools similar to require hook or you can use it to generate json files with tokens for the further usage with a non-JS libraries.

Also I noticed an [issue](https://github.com/posthtml/posthtml/issues/85) in the posthtml, so I believe that it will be used for another plugin :)

**Comment by ai** [comment]
For me `postcss-modules` is just a easy way to use CSS Modules for PHP or Ruby.

I found this tool is extremly complicated. So it can’t be used by CSS guys.

**Comment by geelen** [comment]
Hey @ai can you expand on how you use `postcss-modules` with PHP & Ruby? I'm really interested in that at the moment! :)

**Comment by outpunk** [comment]
@geelen `postcss-modules` provides a callback to save a JSON object with classes for each CSS Module. You can save the returned JSON into separate files next to CSS when you compiling your assets and read these JSON files from PHP/Ruby/whatever code. Like so:
```slim
- styles = JSON.read('front/blocks/logo.json')
div(class=styles['logo'])
  div(class=styles['title'])
```

**Comment by sullenor** [comment]
@ai looks like rumors tell truth :)

Anyways, I think `postcss-modules` provides a good API as another plugin and I like the idea about global comments for the `:global` selector.

I know another person from the PHP world, who was interested in CSS Modules and he talked about similar implementation, like @outpunk mentioned.

**Comment by sullenor** [comment]
I guess we learnt the difference :)
