### ISSUE TITLE
access generated css ?

### ISSUE THREAD

**Issue by themouette** [css-modules/css-modules-require-hook#65]
Is there a clean way to access the generated css?

I understand this is not the initial usage of the hook, so it is ok if there is none, but as it is generated anyway, it would allow to generate both css-module names and css files from babel using [babel-plugin-css-modules-transform](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform).

For now the only alternative is to load a full webpack with [babel-plugin-webpack-loaders](https://github.com/istarkov/babel-plugin-webpack-loaders)

**Comment by sullenor** [comment]
Hi,

Currently you may provide a function through the [`processCss`](https://github.com/css-modules/css-modules-require-hook#processcss-function) option to get the generated css. For each required file it will be called and you'll get the resulting css.

But I'm not sure that it will resolve dependencies in the proper order. The order isn't vital for JS as for CSS.

**Comment by themouette** [comment]
Hi,

From my understanding, by doing this, I will lose the postcss goodness and only access the raw css from sass, less or whatever. Am I mistaken?

**Comment by sullenor** [comment]
Actually, you have two ways to access the CSS: [preprocessCss](https://github.com/css-modules/css-modules-require-hook#preprocesscss-function) and [processCss](https://github.com/css-modules/css-modules-require-hook#processcss-function). The first one is executed before the content of file will be provided to the postcss instance and the second one — after.

**Comment by themouette** [comment]
Great!
thanks a lot.
