### ISSUE TITLE
Auto installing the hook

### ISSUE THREAD

**Issue by just-boris** [css-modules/css-modules-require-hook#70]
I am going to use this hook for my Mocha tests alongside the babel-register for js. So, I supposed to run Mocha using the following command:

```
mocha --compilers js:babel-register,css:css-modules-require-hook
```

But it doesn't work because you export hook, but don't do actual register. So, it would be good to have an ability to setup require hook with default settings by passing a single require statement:

```js
require('css-modules-require-hook/register');
```

What do you think about it?

**Comment by sullenor** [comment]
Actually it was already implemented. You need to specify the external file: [cmrh.conf.js](https://github.com/css-modules/css-modules-require-hook/blob/master/demo/cmrh.conf.js) and call `require('css-modules-require-hook/preset');`

**Comment by just-boris** [comment]
That's exactly that I am looking for. Maybe I did not get this because of its name, but anyway.

Thank you!
