### ISSUE TITLE
Can not use classnames from postcss-style inheritance

### ISSUE THREAD

**Issue by jaybekster** [css-modules/css-modules-require-hook#75]
Hello.
I'm using postcss to write styles and it's inheritance (with ampersand or not).
Code sample:
```
.root {
  propertyName: value;

  &.deepRooted {
    propertyName: value;    
  }
}
```
When I import this and try to use styles.deepRooted - it's `undefined`.

I tired to see what css text processCss method return - and the css is not compiled.

Is this ok? Should I precomplie my postcss by preprocessCss method invokation?

**Comment by sullenor** [comment]
I suppose you miss some plugins for the inheritance implementation. Basically it's not a valid CSS and isn't supported by default.

In case of inheritance is implemented by another postcss plugin — you may use [prepend](https://github.com/css-modules/css-modules-require-hook#prepend-array) prop. If you use another tool for that, then you should provide custom function to the `preprocessCss` prop.

**Comment by jaybekster** [comment]
Thank you. I haven't noticed I required postcss-nested modules for clientside. So added it to prepend medthod.
