### ISSUE TITLE
Adding more caching

### ISSUE THREAD

**Issue by bjrnt** [css-modules/css-modules-require-hook#76]
In our particular use case, we have a couple of large CSS files (>300 KB) that are being required. Each of these takes a long time to parse (the longest about 14 seconds), which means that server start up time is really slow. To deal with this, what we ended up doing was creating a disk cache to avoid having to re-parse all of these huge files every time the server is started (instead they just require a couple of json files, which is very fast). This reduced the server start up time from 40 seconds to about 5 in our particular case.

I was wondering if this kind of functionality is something you'd be interested in incorporating into this repo? If so, I'd be happy to start working on a PR.

**Comment by sullenor** [comment]
Hi,

Thank you for your interest and sorry for my late response. In my opinion, cache functionality can be useful here, but I'm not sure what practice is a good to update it. I wonder what kind of heuristic you used to invalidate cache?

And if you can send a pr — I'll be glad to accept it :) Do you need any help here?

**Comment by bjrnt** [comment]
I looked at [HappyPack](https://github.com/amireh/happypack/blob/267dbc86fffe10896c2cf3e765daf3fadc0d180a/README.md#cachesignaturegenerator-function) which has a similar caching feature, and they're using the `last modified at` timestamp to invalidate cache entries. Do you think this could be a valid approach to use here too? Since the cache only needs to be checked once at start up, I don't think it would introduce any significant overhead. 

I'm planning to start looking through the codebase this week and then check in with you again after I have a suggested design for the feature. If there's anything in particular you'd like me to take into account, please let me know. I'd be grateful for any advice you might have as this is my first time contributing a feature to an open source project!
