### ISSUE TITLE
Use without css modules 

### ISSUE THREAD

**Issue by anri-asaturov** [css-modules/css-modules-require-hook#82]
Is there a way to `<link>` one big css/scss bundle and make components use those global styles without css-modules and other hipster `require(.css)` tricks? :-D

**Comment by anri-asaturov** [comment]
wrong repo, sorry

**Comment by sullenor** [comment]
👍 

I was going to suggest you to try `link` tag and [BEM](https://en.bem.info/methodology/) methodology :)

**Comment by anri-asaturov** [comment]
Hehe, this was meant for react-toolbox repository, where apparently you need both webpack and css-modules.
