### ISSUE TITLE
How to use it on server-side?

### ISSUE THREAD

**Issue by daryn-k** [css-modules/css-modules-require-hook#88]
My server.js file:

```
const hook = require('css-modules-require-hook');

hook({
    generateScopedName: '[name]__[local]___[hash:base64:5]'
});

require('babel-register')({ presets: ['react'] });

import express from 'express';
var app = express();

app.use(express.static('public'));
app.use(require('./routes/index'));

var PORT = 3001;
app.listen(PORT, () => {
    console.log('SERVER IS RUNNING on http://localhost:' + PORT);
});
```

routes/index.js

```
import React from 'react';
import { renderToString } from 'react-dom/server';
import Helmet from "react-helmet"
import { match, RouterContext } from 'react-router';
import { createStore} from 'redux';
import { Provider } from 'react-redux'
import express from 'express'
const router = express.Router();

import reducer from '../reducers';
import routes from './routes';

const store = createStore(reducer);

router.get('*', function(request, response) {

    match({
        routes,
        location: request.url },
        (error, redirect, props) => {
            if(error){
                res.status(500).send(err.message)
            }
            else if (redirect) {
                res.redirect(redirect.pathname + redirect.search)
            }
            else if (props) {
                var html = renderToString(
                    <Provider store={store}>
                        <RouterContext {...props}/>
                    </Provider>
                );
                let head = Helmet.rewind();
                response.send(html);
            } else {
                response.status(404).send('Not Found');
            }
        });

});

module.exports = router;
```
client.js file:

```
import { render } from 'react-dom'
import React from 'react'
import routes from './routes/routes'
import {createStore, applyMiddleware} from 'redux'
import { composeWithDevTools } from 'redux-devtools-extension'
import thunk from 'redux-thunk'
import { Provider } from 'react-redux'

import reducer from './reducers'

var store = createStore(
    reducer,
    composeWithDevTools(applyMiddleware(thunk))
);

console.log('hello world');

render(
    <Provider store={store}>
        {routes}
    </Provider>, document
);
```
When I open browser, many 'hello world' messages appear in console, after that

`Uncaught Error: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side`

How to fix it?

Уважаемый Алексей Литвинов, пожалуйста, не закрывайте эту тему! Если вы не видите server-side rendering, то посмотрите на файл server.js. То, что вы мне скинули ссылку на демо - это не пойдёт. Там не предусмотрено использование роутеров и т.д. Я делаю примерно то же самое, но не получается. Дайте разобраться, не надо сразу закрывать.

**Comment by sullenor** [comment]
Уважаемый, daryn-k 

По вашу скромному описанию очень сложно оценить вашу проблему, а воспроизвести — невозможно. Но, судя по вашему коду и описанию, я несколько сомневаюсь, что она связана с серверным рендерингом и CSS модулями, а скорее похоже на некорректное использование библиотеки `react-dom`.
Поэтому, если вы хотите получить какой-либо детерминированный результат на клиенте и избавиться от варнингов, то не нужно использовать объект document для рендеринга. Вместо этого указывайте существующий узел в DOM-дереве.

Если у вас трудности с использованием CSS модулей, а не `react-*` библиотек, то приходите.

**Comment by daryn-k** [comment]
Алексей, спасибо за ответ. Я всё-таки хочу понять, как css-modules-require-hook использовать в изоморфном приложении. Где есть clients.js и server.js. То, что вы мне скинули ссылку на demo - там этого нет просто-напросто. Так что мой вопрос актуален, как мне кажется.

Будьте добры, скажите, как использовать css-modules-require-hook в isomorphic app?

Код, который выложил - это всё я взял с гитхаба, как образец. Ничего своего не выдумывал.

**Comment by sullenor** [comment]
Тут все просто. CSS модули подразумевают использование аналогичное commonJS модулям, т.е. подключение через вызов функции `require` (и соотв. аналог на es2015 модулях). Пример, `const styles = require('./my-app.css');`.
В силу того, что `require`не умеет работать с CSS файлами, то на уровне сборки это решается при помощи соответствующих плагинов (лоадеров в случае webpack). Таким образом `client.js` является результатом сборки.

На уровне сервера чуть сложнее, т.к. нужно уметь обрабатывать `require` вызовы в рантайме. В качестве решения можно использовать `css-modules-require-hook`, который использует require.extensions и добавляет соответствующий обработчик для `.css` файлов. Подключать его желательно во входной точке сервера. Пример подключения в коде чуть выше вполне подходящий.

**Comment by daryn-k** [comment]
Алексей, снова благодарю за ответ. Сам механизм работы я прекрасно понимаю. И то, что вы написали, я это и так знаю. Проблема в том, как сдружить между собой client.js, server.js и css-modules-require-hook. Без последнего всё хорошо работало. Но как только его подключаешь, всё рушится.

Проблема в том, что вы все очень хорошо объясняете как работать именно с вашей частью (будто-то роуты, css-модули и т.д.). Всё наглядно, вон рабочие примеры есть. Но как только надо их вместе использовать - тут вообще ничего непонятно, просто каша.

**Comment by sullenor** [comment]
Ну тут все просто, если вы хотите развеять мои сомнения, то прикладывайте копию проекта. В противном случае не вижу смысла продолжать.

**Comment by sullenor** [comment]
Необязательно копию всего проекта, достаточно минимальный пример, который воспроизводит проблему, т.к. сообщение об ошибке довольно общее и по нему нет возможности судить, что проблема в подключении модулей.

**Comment by daryn-k** [comment]
Я уже с психу удалил весь проект. Начну заново. На основе этого demo. Извините за беспокойство, гуру из Яндекса.

**Comment by sullenor** [comment]
Гуру тоже могут ошибаться. Действительно, стандартов нет и каждый пишет по-своему, в силу тех или иных требований, в результате появляется множество решений. Я попробую еще раз объяснить, что меня смутило, чтобы избежать возможных ошибок.

Чуть выше вы приводили сообщение об ошибке

> Uncaught Error: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side

которую может выдать реакт при рендере на клиенте в случае, если существующая разметка не совпадает с той, которую вы пытаетесь отрендерить. Причин может быть много. Например, состояние (в redux) на клиенте отличается от того, что было на сервере. Другая, частая причина, когда в качестве узла указывают `document.body` в силу того, что в body уже содержит дополнительную разметку (скрипты или результат работы скриптов, браузерных расширений и т.п.) и гарантировать детеминированное состояние тут сложно. Обычно, в этом случае создают пустой `div`, в который и рендерят приложение (и ссылаются на него как-то так: `document.querySelector('#entry')`). В вашем же примере использовался просто `document`, который содержит информацию о странице, но никак не является конечным узлом (допускаю, что это могла быть опечатка).
Если, в этом месте нет проблем, то может быть проблема с генерацией токенов (уникальных классов). Проверить это можно простым сравнением разметки, которая пришла с сервера с той, что была сформирована на клиенте. Если это действительно так, то тут надо смотреть на конфигурацию (чаще всего проблема возникает с путями из-за расхождения рабочей директории).

**Comment by sullenor** [comment]
У меня был еще небольшой пример, правда без роутера, можно посмотреть там, как это работает: https://github.com/sullenor/todos

**Comment by daryn-k** [comment]
Алексей, спасибо за очередной ответ. Я прекрасно и до этого знал то, о чём вы написали. Принцип работы мне итак понятен. Свою мысль я, наверное, сформулирую так: я не могу собрать или найти нужный мне boilerplate, где уже есть: react, redux, webpack, css, jsx, router. Везде чего-то не хватает. Уже несколько недель сижу и не могу собрать это.

На вашем демо я сейчас убиваю кучу времени, чтобы элементарно настроить jsx. Это нормально? Нет, это ненормально.

**Comment by daryn-k** [comment]
Всё, я уже разобрался. Всё работает. Переписал проект. Оказалось, что я за boilerplate взял проект какого-то криворукого программиста на react - вот он: https://github.com/remarkablemark/universal-react-tutorial Оттуда корни всех проблем.
